export const Users = [
  {
    id: 1,
    profilePicture: "person/1.jpeg",
    username: "poonam",
  },
  {
    id: 2,
    profilePicture: "person/2.jpeg",
    username: "dolly",
  },
  {
    id: 3,
    profilePicture: "person/3.jpeg.jpeg",
    username: "ashish",
  },
  {
    id: 4,
    profilePicture: "person/4.jpeg",
    username: "kabbu",
  },
  {
    id: 5,
    profilePicture: "person/5.jpeg",
    username: "anshu",
  },
  {
    id: 6,
    profilePicture: "person/6.jpeg",
    username: "nitin",
  },
  {
    id: 7,
    profilePicture: "person/7.jpeg",
    username: "khushboo",
  },
  {
    id: 8,
    profilePicture: "person/8.jpeg",
    username: "preeti",
  },
];
 export const Posts=[
    {
        id:1,
        desc:"love you all",
        photo:"person/1.jpeg",
        date:"5 mins ago",
        userId:1,
        like:32,
        comment:9,
    },
    {
        id:2,
        desc:"hi there",
        photo:"person/2.jpeg",
        date:"10 mins ago",
        userId:2,
        like:105,
        comment:15,
    },
    {
        id:3,
        desc:"in a sunny day",
        photo:"person/3.jpeg.jpeg",
        date:"15 mins ago",
        userId:3,
        like:256,
        comment:89,
    },
    {
        id:4,
        desc:"sunshine",
        photo:"person/4.jpeg",
        date:"25 mins ago",
        userId:4,
        like:532,
        comment:92,
    },
    {
        id:5,
        desc:"be you ",
        photo:"person/5.jpeg",
        date:"5 mins ago",
        userId:5,
        like:326,
        comment:88,
    },
    {
        id:6,
        photo:"person/6.jpeg",
        date:"10 mins ago",
        userId:6,
        like:302,
        comment:9,
    },
    {
        id:7,
        desc:"love those who need it",
        photo:"person/7.jpeg",
        date:"5 mins ago",
        userId:7,
        like:32,
        comment:9,
    },
    {
        id:8,
        desc:"fall in love again!",
        photo:"person/8.jpeg",
        date:"50 mins ago",
        userId:8,
        like:592,
        comment:59,
    },
 ]
